adobe/helix-pipeline

README.md, src/utils/index.js, src/utils/match-section-types.js, src/utils/pattern-compiler.js, test/testPatternCompiler.js, test/testTypeMatcher.js
This is a WIP implementation of #50 that does not require developers to build state machines from hand or to learn a new API to match sequences of elements, because it is simply using Regular expressions.
For instance to identify a "Gallery", i.e. a section that has at least three images, and maybe a heading, use `^heading? image image image+$`.
To identify a section that has only lists or paragraphs (and maybe a heading in the beginning), use `^heading? (paragraph|list)+$`.
It is intended to work with #47 and uses the new `utils` namespace from #53, so that it can be called from `pre.js`
Still outstanding:
=> Section Pattern Matching Language inspired by RegExp

src/defaults/html.pipe.js, src/html/fetch-markdown.js, src/html/set-surrogate-key.js, test/testHTML.js
Fixes #23 
Each URL that is fetched individually to render the content should be listed in `content.sources`.
Each URL in `content.sources` will then be sha256 hashed and added to `Surrogate-Keys`.
If you want to write a selective cache invalidator (👋 @tripodsan), go over each file in the commit event, and go over each name of the commit (e.g. branch or tag names when pushed), calculate the `raw.githubusercontent.com` URL and get the hash.
=> Surrogate keys

src/defaults/json.pipe.js, src/defaults/json.pre.js, src/json/set-content-type.js, test/testJSON.js
This is a a dirt-simple JSON pipeline, based on the HTML pipeline.
It is completely unopinionated when it comes to representing your JSON document and just expects your main function to set `response.body` to an object.
Fixes #16
=> Simple JSON Pipeline

.gitignore, README.md, package-lock.json, package.json, src/defaults/html.pipe.js, src/defaults/json.pipe.js, src/pipeline.js, src/utils/dump-context.js, src/utils/is-production.js, test/testDebugTmp.js, test/testHTML.js, test/testIsProduction.js, test/testPipeline.js
This fixes #14 and provides an alternative to #19:
when running in development-mode (i.e. no OpenWhisk in sight), every step of pipeline processing will be dumped in the `debug` directory. This allows for very fine-grained inspection of the pipeline processing.
The new `Pipeline.tap` helper function allows the registration of effect-less observers or validators.
=> Tap Pipeline & Dump Context for Debugging

docs/action.schema.json, docs/action.schema.md, package.json, src/action.d.ts, src/schemas/action.schema.json, src/utils/dump-context.js
see #89 
**Note**: I removed the `tmp` dependency, as it would always create random chars for the directory name, which cannot be disabled. also, its feature to cleanup automatically never worked for me. I think it doesn't work, if the process is stopped with `ctrl+c`.
example layout:
```
logs/debug/
├── context_dump_20181006-0156-29.0414_e23c5b809a418618e7fe1815f373f90a/
│   ├── context-20181006-0156-29.0414-step-0.json
│   └── context-20181006-0156-29.0469-step-12.json
├── context_dump_20181006-0158-53.0514_43e4948ff00588cbbc5e66e453ad4ae8/
│   ├── context-20181006-0158-53.0514-step-0.json
│   └── context-20181006-0158-53.0572-step-12.json
└── context_dump_20181006-0159-59.0749_e9216df0c300fa922b70c674bc0dc62c/
├── context-20181006-0159-59.0749-step-0.json
├── …
```
=> tap logs not usefully grouped #89

src/defaults/conditional-sections.js, src/defaults/html.pipe.js, src/schemas/rawrequest.schema.json, src/utils/conditional-sections.js, test/testConditionalSections.js
This is a partial implementation of #57, it will mark all sections that have a `strain` metadata value that does not match the currently selected strain as `hidden: true`. The sections are not actually removed, but should be skipped when rendering.
=> Mark sections as hidden when strain parameter does not match

docs/secrets.schema.json, docs/secrets.schema.md, package-lock.json, package.json, src/html/embed-whitelist.json, src/html/fetch-markdown.js, src/html/find-embeds.js, src/pipeline.js, src/schemas/secrets.schema.json, src/utils/coerce-secrets.js, src/utils/embed-handler.js, src/utils/image-handler.js, src/utils/validate.js, src/utils/validator.js, test/testCoercer.js, test/testEmbedHandler.js, test/testFetchMarkdown.js, test/testFindEmbeds.js, test/testImageHandler.js, test/testMdastToVDOM.js, test/testOpenwhisk.js
This is an implementation of #108 
The `coerce` function uses the ability of the `ajv` JSON Schema validator to set defaults that are defined in the schema, but not in the passed object, and to coerce string values into more specific values. As a result, all configuration properties that are documented in the `secrets.schema.json` will be present in the `action` and have the proper type.
=> Refactor defaults

src/defaults/html.pipe.js, src/utils/conditional-sections.js, test/testConditionalSections.js
This is part II of #57 
By adding `test: groupname` to the front matter of multiple sections, the pipeline will randomly, but repeatably (using the strain name as random seed) pick exactly one section with that particular name of the test group and hide all others.
=> Conditional sections based on A/B testing

docs/content.schema.json, docs/content.schema.md, docs/mdast.schema.json, docs/mdast.schema.md, package-lock.json, package.json, src/action.d.ts, src/context.d.ts, src/defaults/html.pipe.js, src/html/emit-html.js, src/schemas/content.schema.json, src/schemas/mdast.schema.json, src/utils/mdast-to-vdom.js, test/testEmbedHandler.js, test/testEmitHTML.js, test/testHTMLFromMarkdown.js, test/testMdastToVDOM.js
This fixes two issues with markdown rendering and adds an infrastructure for testing whether for a specific markdown input, the correct output is produced.
Not sure whether `test/testHTMLFromMarkdown.js` should not be merged into `test/testHTML.js`; I kind of like having all the markdown tests in their own place, on the other hand a lot of boilerplate is required to put them there…
=> Fix problems in the markdown -> html pipeline

test/fixtures/headings.json, test/fixtures/headings.md, test/testParseMarkdown.js
Added a test to show that underlined headings as described in #155 currently do not parse as expected.
=> test headings (skipped) #155

package-lock.json, package.json, src/html/parse-markdown.js, test/fixtures/headings.json, test/fixtures/headings.md, test/testParseMarkdown.js
As discussed in #155, I removed the line im parse-markdown.js that caused setext headings to be ignored. Also added a test to show that both setext and # headings are processed correctly.
=> md parser regression: setext headings no longer work #155

src/defaults/html.pipe.js, src/html/set-status.js, test/testSetStatus.js
=> display more useful output on errors #187

package-lock.json, package.json, src/html/fetch-markdown.js, test/fixtures/Test-non-existing-content_3508203637/Getting-XDM-README-from-wrong-URL-_3748211873/recording.har, test/fixtures/Test-non-existing-content_3508203637/Getting-XDM-README-with-missing-ref-_3627027906/recording.har, test/fixtures/Test-requests_3022673737/Getting-XDM-README_4219425422/recording.har, test/fixtures/Testing-HTML-Pipeline_3038423338/html-pipe-keeps-existing-headers_3629209091/recording.har, test/fixtures/Testing-HTML-Pipeline_3038423338/html-pipe-makes-HTTP-requests-and-falls-back-to-master_2961813882/recording.har, test/fixtures/Testing-HTML-Pipeline_3038423338/html-pipe-makes-HTTP-requests_1846604431/recording.har, test/fixtures/Testing-HTML-Pipeline_3038423338/html-pipe-produces-debug-dumps_816111615/recording.har, test/fixtures/Testing-HTML-Pipeline_3038423338/html-pipe-serves-404-for-non-existent-content_254320879/recording.har, test/fixtures/Testing-JSON-Pipeline_1774802251/json-pipe-keeps-Mime-Type_3820175046/recording.har, test/fixtures/Testing-JSON-Pipeline_1774802251/json-pipe-makes-HTTP-requests_1827123166/recording.har, test/fixtures/Testing-XML-Pipeline_1741549992/xml-pipe-detects-ESI-tag-in-XML-object_3288113526/recording.har, test/fixtures/Testing-XML-Pipeline_1741549992/xml-pipe-makes-HTTP-requests_607214737/recording.har, test/fixtures/Testing-XML-Pipeline_1741549992/xml-pipe-serves-404-for-non-existent-content_1812732349/recording.har, test/fixtures/Testing-XML-Pipeline_1741549992/xmp-pipe-does-not-overwrite-existing-respone-body_988789528/recording.har, test/fixtures/Testing-XML-Pipeline_1741549992/xmp-pipe-uses-default-logger-if-none-provided_3867768995/recording.har, test/testFetchMarkdown.js
Pollyjs broke some compatibility in moving to 2.1.0 (replacing their native implementation with `nock`, therefore #172 and #171 have been failing.
This PR fixes the tests.
=> Pollyjs update

.circleci/config.yml, CONTRIBUTING.md, package-lock.json, package.json
Fix for #190 
Biggest change for developers is described in the update to `CONTRIBUTING.md`: you have to run `npm run commit` to generate a commit message. Upon merging into `master`, the release will automatically get a semantically appropriate version number.
=> Introduce Semantic release

README.md, src/html/get-metadata.js, test/fixtures/sections/2images.json, test/fixtures/sections/2images.md, test/fixtures/sections/complex.json, test/fixtures/sections/headerimage.json, test/fixtures/sections/headerlist.json, test/fixtures/sections/headerpara2images.json, test/fixtures/sections/headerparagraph.json, test/fixtures/sections/headerparaimage.json, test/fixtures/sections/paragraph.json, test/fixtures/sections/paragraphwithlink.json, test/fixtures/sections/paragraphwithlink.md, test/testGetMetadata.js
PR for #201 
This changes quite some little details on how the types for paragraphs are handled:
* the "paragraph" type disappear: a paragraph (p tag) can be an image only or a link only. The notion of paragraph is biased. Replacing the "paragraph" type by the "text" type makes much more sense: a p can then be a text, image or link and a paragraph can have images, links...
* `has-paragraph` and `is-paragraph` becomes then `has-text` and `is-text`
* manages some edge cases like empty text (line break between 2 images for example would generate a useless text paragraph)
From the issue
```md
This is a paragraph with a [link](/index.html)!
```
will now generate:
* section types: `has-text has-link nb-text-2 nb-link-1 is-text-link is-text`
* paragraph types: `is-text has-link`
This is a …
=> Section and subitems type is wrong for paragraph with a link

docs/mdast.schema.json, docs/mdast.schema.md, src/schemas/mdast.schema.json, test/fixtures/index-modified.md, test/testHTMLFromMarkdown.js
Adds the neccessary schema for referenceType and a corresponding integration test
fixes #159 needed by https://github.com/adobe/helix-cli/pull/653
=> fix(markdown): Fix handling of references in Markdown validation

src/pipeline.js, src/utils/validate.js, src/utils/validator.js, test/testHTML.js
PR (no issue) to improve error logs.
Instead of
```
[hlx] warn: tapping failed: ReferenceError: addListMetadata is not definedaddListMetadata is not defined
```
you get now
```
[hlx] error: tapping failed: ReferenceError: addListMetadata is not defined
at Object.filter (/Users/alex/work/dev/helix/hackathon/helix-sections-playground/.hlx/build/superfilter.js:40:3)
at c.sections.forEach (/Users/alex/work/dev/helix/hackathon/helix-sections-playground/.hlx/build/object_json.js:22:17)
at Array.forEach (<anonymous>)
at main (/Users/alex/work/dev/helix/hackathon/helix-sections-playground/.hlx/build/object_json.js:21:14)
at invoker (/Users/alex/work/dev/helix/hackathon/helix-sections-playground/.hlx/build/object_json.js:53:32)
```
And
Instead of
```
[hlx] warn: Invalid Context at step 6, …
```
=> chore: improve error logs

src/utils/dump-context.js
PR for #248
Added the request path inside the folder name (slashes replaced by dashes).
For the following set of requests (in this order):
1. http://localhost:3000/index.html
1. http://localhost:3000/docs/ROLLOUT.html
1. http://localhost:3000/xd/doc/README.html
1. http://localhost:3000/index.html?debug=true
`ls -tl` will show the following "context dump" folders:
```
drwxr-xr-x  19 alex  staff  608 Apr 10 10:14 context_dump_index.default.html_20190310-0814-17.0133_741d12cbea5472965d966dbc5e75d3dc
drwxr-xr-x  19 alex  staff  608 Apr 10 10:14 context_dump_index.html_20190310-0814-16.0591_2dafb5fbea54ff17bfbf18c472da736e
drwxr-xr-x   4 alex  staff  128 Apr 10 10:14 context_dump_xd-doc-README.html_20190310-0814-11.0171_d5eb823d59694513aad62dcddf715647
drwxr-xr-x  19 alex  staff  608 Apr 10 …
```
=>  feat(logs): Make context dump subdirectory names be more meaningful

src/utils/heading-handler.js, test/fixtures/heading-ids.json, test/fixtures/heading-ids.md, test/testMdastToVDOM.js
Properly support complex headers that include child elements (strong, em, code, etc.) when
automatically generating the heading identifiers
This is a follow-up to #240 as @trieloff identified a remaining bug in the implementation as complex headings were not supported.
fix #26
=> fix(html pipe): Generate proper identifiers for complex headings

package.json
until nyc 14.1.0 is released.
Fixes #282
=> test(pipe): temporarily disable lcov reporter

src/html/find-embeds.js, src/schemas/secrets.schema.json, src/utils/embed-handler.js, src/utils/mdast-to-vdom.js, test/fixtures/embeds.json, test/fixtures/embeds.md, test/testConditionalSections.js, test/testEmbedHandler.js, test/testFindEmbeds.js, test/testHTML.js, test/testHTMLFromMarkdown.js
=> Support Internal Embeds

src/defaults/html.pipe.js, src/defaults/json.pipe.js, src/defaults/xml.pipe.js, src/pipeline.js, src/utils/timing.js, test/testPipeline.js
=> feat(pipe): add timing information and clean up function name reporting

docs/secrets.schema.json, docs/secrets.schema.md, package-lock.json, package.json, src/action.d.ts, src/defaults/html.pipe.js, src/schemas/secrets.schema.json, src/utils/resolve-ref.js, test/fixtures/Test-resolve-git-ref_2496004244/Resolve-resolves-master-ref-correctly-_4084244876/recording.har, test/fixtures/Test-resolve-git-ref_2496004244/Resolve-resolves-master-ref-correctly-using-openwhisk-_275354344/recording.har, test/fixtures/Test-resolve-git-ref_2496004244/Resolve-resolves-missing-ref-as-master-correctly-_3792802480/recording.har, test/testResolveRef.js
fixes #382
I currently set the the API endpoint in the secrets schema to the empty string.
```
"RESOLVE_GITREF_SERVICE": {
"type": "string",
"description": "API endpoint to micro service that resolves github refs to commit SHAs.",
"default": ""
}
```
This has the advantage, that all action don't use the new lookup right away. so for it to work, we also need to set the action param during `hlx deploy`. This will be required anyways, because we want to execute the lookup action in the users namespace and not the helix one.
=> feat(fetch): resolve github ref to commit sha

src/html/unwrap-sole-images.js, test/testHTMLFromMarkdown.js
Unwrap sole images in a single paragraph in a section so the hero image is not inside a paragraph tag
(follow-up of dbcf627 to support new sections)
fix #338
=> feat(html pipe): Unwrap hero images

src/html/fetch-markdown.js
corrected `timout` to `timeout`
```
[hlx] error: Gateway timout of 1000 milliseconds exceeded for ...
```
=> chore(log): corrected misspelling

README.md, package-lock.json, package.json, src/html/make-html.js, src/html/parse-markdown.js, src/schemas/action.schema.json, src/utils/mdast-to-vdom.js, test/testHTMLOverrides.js, test/testMdastToVDOM.js
Fixes #325 
Manually creating the VDOM Transformer in `pre.js` was always dependent on making sure that all updates to `content.mdast` got intercepted. By exposing the transformer in `action.transformer`, it can be hooked into easily by adding a `exports.before.html` extension function that adds new `action.transformer.match()` calls.
The documentation has been updated to reflect the new usage pattern and references to the removed responsifier #380 have been removed.
=> Expose VDOM Transformer in Action

src/html/parse-frontmatter.js, test/testFrontmatter.js, test/testGetMetadata.js, test/testParseMarkdown.js, test/testSplitSections.js
- no longer throw exceptions (we need to think about how to report this)
- do not require non-empty lines in the front matter block at the start of the document (same rules for other blocks)
fixes #441
=> Relax Frontmatter Parsing

src/html/find-embeds.js, test/testEmbedHandler.js
The embed handler would have troubles with `mailto:` links. The fix is checking that candidates for an embed link are HTTP or HTTPS based and will have a real hostname
fixes https://github.com/adobe/helix-pages/issues/83
=> fix(pipeline): repair mailto link handling in embed processing

src/html/parse-markdown.js, test/testParseMarkdown.js
PR for https://github.com/adobe/helix-pipeline/issues/472
Did not find how to do that simply (and user readable) with Ferrum. Back to good old `if`.
Also added tests for uncovered area.
=> fix(parse): fix empty extension case and add tests

src/html/find-embeds.js, test/testEmbedHandler.js
This PR fixes #511 by making the detection of IA embeds a bit more restrictive
- only embeds in paragraphs directly below the root node are accepted (no more embeds in list items)
- only embeds where the link text equals the URL are accepted (no random single YouTube links turn into embeds anymore)
=> Restrict embeds

package-lock.json, src/utils/image-handler.js, src/utils/mdast-to-vdom.js, test/fixtures/image-example.html, test/fixtures/image-example.md, test/testMdastToVDOM.js
When using the Azure Blob store, for instance through `helix-googledocs2md` or `helix-word2md`, image links point directly to the Azure Blob store. This change replaces these URLs in the HTML output with links to the `hlx_*.jpg`, i.e. Blob Proxy support, so that images can be resized and delivered from the same domain as the main content.
fixes https://github.com/adobe/helix-word2md/issues/128 fixes https://github.com/adobe/helix-googledocs2md/issues/133 closes https://github.com/adobe/helix-word2md/pull/129 requires https://github.com/adobe/helix-publish/pull/278 supports https://github.com/davidnuescheler/theblog/issues/43
=> feat(html): rewrite image URL for Azure Blob store

src/utils/embed-handler.js, test/testEmbedHandler.js
the embed service expects the to-be-embedded URL to be passed after a trailing slash. The code did
not add the trailing slash, making it impossible for Adobe I/O Runtime to find the correct action to
execute. This change adds the correct slash again.
fixes https://github.com/adobe/helix-embed/issues/145 fixes #559
=> fix(embed): fix external embed service URL construction

src/utils/Downloader.js
provides an extra way (via the `HELIX_PIPELINE_FORCE_HTTP1` process env) to force http1 for helix-fetch. this is especially useful for tests that want to use pollyjs/nock but don't have a direct access to the pipeline action.
**Note**: After this is fixed, we need to update some of the `helix-cli` tests (eg: `testUpCmd.js`) to set the process env. for example:
```patch
diff --git a/test/testUpCmd.js b/test/testUpCmd.js
index 0c3bafe..ed565db 100644
--- a/test/testUpCmd.js
+++ b/test/testUpCmd.js
@@ -60,6 +60,7 @@ describe('Integration test for up command', function suite() {
});
beforeEach(async function beforeEach() {
+    process.env.HELIX_PIPELINE_FORCE_HTTP1 = true;
this.polly.server.any()
.filter((req) => req.headers.host.startsWith('localhost') || …
```
=> feat(pipeline): add options to force http1 for tests

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/discussion.md, .github/ISSUE_TEMPLATE/feature_request.md
For some reason, helix-pipeline has been missing these. I've taken the liberty to rephrase the bug report template a bit.
=> create issue templates

package-lock.json, src/html/fetch-content.js, test/testFetchContent.js
re-adds the `content.data.sourcehash` that was lost during content-proxy replacement
=> Source hash

docs/meta-definitions-meta-properties.md, docs/rawrequest-definitions-rawrequest-properties.md, docs/section-definitions-section-properties.md, package-lock.json, src/html/fetch-content.js
When requesting a resource from Fastly content-proxy, do not cache the response.
=> fix: do not cache responses to Fastly content-proxy

src/utils/Downloader.js, test/testDownloader.js
adds support for gh-pages using the branch name to select a different github _root_.
see https://github.com/adobe/helix-home/issues/191
=> feat(content): add support for github pages

src/html/rewrite-blob-images.js, test/fixtures/image-example.json, test/fixtures/image-rewritten-example.html, test/testRewriteBlobImages.js
with the inclusion of the image dimensions, we should remove them when rewriting the image urls to the media-urls, until the helix-pages picture handling is adjusted accordingly.
=> fix: respect image hashes with dimensions
