adobe/helix-pipeline

- package-lock.json
- package.json
- src/helper.js
- src/html/fetch-markdown.js
- test/testFetchMarkdown.js
- test/testHelper.js
> Better error handling and URL handling for fetch-markdown

- src/html/get-metadata.js
- test/testGetMetadata.js
> `Cannot convert undefined or null to object` while running the pipeline

- package-lock.json
- package.json
- src/html/get-metadata.js
> Drop the `yaml` dependency in favor of `js-yaml`

- package.json
> fix(package): update hast-util-to-html to version 4.0.1

- README.md
- package-lock.json
- package.json
- src/html/emit-html.js
- src/html/fetch-markdown.js
- src/html/get-metadata.js
- src/html/make-html.js
- src/html/parse-markdown.js
- src/html/responsify-images.js
- test/testFetchMarkdown.js
- test/testGetMetadata.js
- test/testHTML.js
> Rename 'resource' to 'content' 

- src/defaults/default.js
- test/testDefault.js
ensure compatibility with adobe/helix-cli#153
> Parse params parameter to get request parameters

- src/defaults/html.pipe.js
- test/testHTML.js
- test/testPipeline.js
fixes #13
- this could be useful for you, @rofe
> Skip the fetch step if there is already a body

- README.md
- src/defaults/html.pipe.js
- src/defaults/json.pipe.js
- src/pipeline.js
- test/testPipeline.js
> renamed pre to before and post to after

- .eslintrc.js
- index.js
- package-lock.json
- package.json
- src/defaults/default.js
- src/defaults/html.pipe.js
- src/defaults/json.pipe.js
- src/utils/openwhisk.js
- test/testDefault.js
- test/testFetchMarkdown.js
- test/testHTML.js
- test/testJSON.js
- test/testOpenwhisk.js
see #46 
- provides new openwhisk adapter functionality in `openwhisk.js`
- moves adaptOWRequest and adaptOWResponse out of pipeline
>  Add all owrequest adapter logic from helix-cli #46

- src/html/set-surrogate-key.js
- test/testHTML.js
> Switched surrogate keys to base64

- package-lock.json
- package.json
- src/pipeline.js
- test/testPipeline.js
> Parse the call stack for better log messages

- .vscode/launch.json
- package-lock.json
- package.json
- test/fixtures/confusing.json
- test/fixtures/example.json
- test/fixtures/frontmatter.json
- test/fixtures/grayscale.json
- test/fixtures/sections.json
- test/fixtures/sectionsmetadata.json
- test/fixtures/simple.json
- test/fixtures/smartypants.json
- test/markdown-utils.js
PR for https://github.com/adobe/hypermedia-pipeline/issues/87
> Improve tests: remove position information #87

- src/schemas/mdast.schema.json
> JSON validation fails for code meta which can be null #93

- package-lock.json
- src/html/get-metadata.js
- test/fixtures/index-modified.md
- test/fixtures/index-unmodified.md
- test/testHTML.js
> Fix for Regression in metadata extraction

- src/defaults/html.pipe.js
- src/html/shared-cache.js
- test/testHTML.js
> Setting shared cache to one week

- src/defaults/html.pipe.js
- src/html/flag-esi.js
- test/testHTML.js
> Flag ESI in Response

- package-lock.json
- src/html/emit-html.js
- test/testEmitHTML.js
> [Regression] payload.content.children contains only one child #115

- package-lock.json
- package.json
- src/html/make-html.js
- src/schemas/secrets.schema.json
- src/utils/image-handler.js
- src/utils/link-handler.js
- src/utils/mdast-to-vdom.js
- test/fixtures/paragraph.json
- test/testLinkHandler.js
- test/testMdastToVDOM.js
> Rewrite Links in HTML #25

- bin/schema2ts.js
- package-lock.json
- package.json
See also adobe/openwhisk-loggly-wrapper#11
> make dev dependencies dev-only

- docs/request.schema.json
- package-lock.json
- package.json
- src/schemas/request.schema.json
- src/utils/openwhisk.js
- test/testOpenwhisk.js
> Consolidate request properties in dev and publish env #140

- src/utils/is-production.js
- test/testIsProduction.js
Fixes #142, helps with adobe/helix-cli#408
> Robust production

- src/html/fetch-markdown.js
- test/testFetchMarkdown.js
- test/testHTML.js
> Fall back to master if ref isn't set

- .npmignore
> strip unnecessary weight from published npm package #146

- src/html/fetch-markdown.js
- src/schemas/secrets.schema.json
- test/fixtures/Test-non-existing-content_3508203637/Getting-XDM-README-with-missing-ref-_3627027906/recording.har
- test/fixtures/Testing-HTML-Pipeline_3038423338/html-pipe-makes-HTTP-requests-and-falls-back-to-master_2961813882/recording.har
- test/testConditionalSections.js
- test/testFetchMarkdown.js
> Timeouts for HTTP Client

- package-lock.json
- package.json
```
=== npm audit security report ===                        
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ handlebars                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ nyc [dev]                                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ nyc > istanbul-reports > handlebars                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More …
```
> fix security issues with nyc and handlebars

- src/html/get-metadata.js
- test/fixtures/sections/complex.json
- test/fixtures/sections/headerlist.json
Not sure what happened but the constructed types for lists piece was missing... 
Follow up PR for #112
> List Comprehension #112

- src/pipeline.js
Minor PR that includes the full stack trace for errors in `tap`
> fix(pipeline): don't hide stack trace from errors

- .circleci/config.yml
PR for https://github.com/adobe/helix-continuous/issues/9
> Smoke test workflow sporadically fails while smoke tests were successful

- .circleci/config.yml
- .releaserc.js
- package.json
> fix(release): semantic-release now updates package.json

- src/schemas/mdast.schema.json
- test/testHTMLFromMarkdown.js
Will merge tomorrow around the end of the workday (CEST)
> fix(markdown): #158 GFM Tables crash the pipeline

- src/utils/openwhisk.js
- test/testOpenwhisk.js
> properly propagate error in action response

- src/utils/openwhisk.js
- test/testOpenwhisk.js
> fix(openwhisk): directory index information is not available anymore

- docs/request.schema.json
- docs/request.schema.md
- src/context.d.ts
- src/schemas/request.schema.json
- src/utils/openwhisk.js
- test/testOpenwhisk.js
> feat(openwhisk): add request.pathInfo

- README.md
> docs(extensions): document the new before/after extension points

- package-lock.json
- package.json
- src/utils/heading-handler.js
- src/utils/mdast-to-vdom.js
- test/fixtures/forms.json
- test/fixtures/forms.md
- test/testHTMLFromMarkdown.js
- test/testParseMarkdown.js
The people have spoken. The people want to live dangerously. The people want to have HTML in their markdown. 
Fixes #154
> Dangerous HTML

- src/defaults/json.pipe.js
- src/json/emit-json.js
- src/json/set-json-status.js
- src/schemas/content.schema.json
- test/fixtures/Testing-JSON-Pipeline_1774802251/json-pipe-can-be-extended_3521048475/recording.har
- test/fixtures/Testing-JSON-Pipeline_1774802251/json-pipe-does-not-overwrite-existing-response-body_1311785260/recording.har
- test/testEmitJSON.js
- test/testJSON.js
- test/testSetJSONStatus.js
- fix #230: emit json from content.json
- fix #269: expose extension points
- fix #280: don't bleed errors in production
> feat(json): refactoring json pipeline

- src/defaults/html.pipe.js
> feat(html): introduce new hast extension point

- src/defaults/default.js
- src/defaults/html.pipe.js
- src/defaults/json.pipe.js
- src/defaults/xml.pipe.js
- src/html/flag-esi.js
- src/html/output-debug.js
- src/html/set-status.js
- src/json/set-json-status.js
- src/utils/openwhisk.js
- src/xml/set-xml-status.js
- test/testCheckXML.js
- test/testDefault.js
- test/testEmitXML.js
- test/testOpenwhisk.js
- test/testOutputDebug.js
- test/testSetContentType.js
- test/testXML.js
> chore(refactor): consistently use `context` instead of payload.

- src/defaults/html.pipe.js
- src/pipeline.js
- test/testHTML.js
- test/testHTMLFromMarkdown.js
> feat(html-pipe): disable sanitizer by default

- src/defaults/html.pipe.js
- src/schemas/secrets.schema.json
- test/testHTML.js
- test/testHTMLFromMarkdown.js
> Update secrets schema

- src/utils/validator.js
> fix(validator): avoid dynamic require

- src/utils/openwhisk.js
- test/fixtures/Testing-HTML-Pipeline_3038423338/html-pipe-via-pipeline-fetch-errors-are-propagated-to-action-response_2359812822/recording.har
- test/testHTML.js
- test/testOpenwhisk.js
> fix(openwhisk): never set the 'error' property of the response.

- src/defaults/html.pipe.js
- src/defaults/json.pipe.js
- src/defaults/xml.pipe.js
- src/utils/dump-context.js
- test/testDebugTmp.js
- test/testHTML.js
- test/testXML.js
> feat(pipe): keep context dumps in memory

- src/utils/openwhisk.js
- test/testHTML.js
- test/testOpenwhisk.js
> feat(error): add response.errorStack for additional information.

- src/html/set-surrogate-key.js
- test/testHTML.js
> feat(caching): use computeSurrogateKey from helix-shared

- docs/content.schema.json
- docs/content.schema.md
- src/context.d.ts
- src/schemas/content.schema.json
> feat(schema): Add context.content.data

- src/utils/resolve-ref.js
- test/testResolveRef.js
> fix(pipeline): ignore warning for git-resolve against localhost

- src/utils/openwhisk.js
- test/testOpenwhisk.js
> fix(pipe): ensure request.headers is present

- docs/rawrequest.schema.json
- docs/rawrequest.schema.md
- src/action.d.ts
- src/html/fetch-markdown.js
- src/schemas/rawrequest.schema.json
- test/fixtures/Testing-HTML-Pipeline_3038423338/html-pipe-makes-HTTP-requests-and-prefers-branch-param-for-surrogate-computationr_101394306/recording.har
- test/testHTML.js
> fix(cache): compute surrogate-key based on branch

- src/html/set-status.js
- src/json/set-json-status.js
- src/xml/set-xml-status.js
- test/testSetJSONStatus.js
- test/testSetStatus.js
- test/testSetXMLStatus.js
> feat(pipe): turn off error-suppression in production when X-Debug: true

- src/html/find-embeds.js
> refactor(embed): change embed whitelist log level to debug (#321)

- docs/request.schema.json
- docs/request.schema.md
- package-lock.json
- src/schemas/request.schema.json
- src/utils/openwhisk.js
- test/testOpenwhisk.js
https://github.com/adobe/helix-pipeline/issues/366
> feat(pipe): added queryString property

- src/defaults/default.js
- src/defaults/html.pipe.js
- src/defaults/json.pipe.js
- src/defaults/xml.pipe.js
> fix(all pipe): reduce schema validation error reporting

- README.md
fix issue #475 
changed occurence to occurrence in two places.
> update readme - typo fix

- README.md
Fixed grammar issues in the README.
> docs: correct grammar of README

- .npmignore
- .snyk
- package-lock.json
- package.json
remove snyk dependency from package.json
fix #491
> build(package.json): remove snyk dependency

- src/html/get-metadata.js
- test/fixtures/sections/herosection.json
- test/fixtures/sections/herosection.md
- test/testGetMetadata.js
> Hero section title

- src/utils/openwhisk.js
winston logger is compatible through logger.log already
fix #543
> fix(openwhisk.js): fix bottomless recursion issue

- src/utils/mdast-to-vdom.js
- test/fixtures/Test-non-existing-content_3508203637/Getting-XDM-README-from-wrong-URL-_3748211873/recording.har
- test/fixtures/Test-non-existing-content_3508203637/Getting-XDM-README-with-missing-ref-_3627027906/recording.har
- test/fixtures/tags.html
- test/fixtures/tags.md
- test/testFetchMarkdown.js
- test/testMdastToVDOM.js
see #583 
Note: this PR also includes updated polly recording in a separate commit.
> Faster vdom generation

- src/utils/Downloader.js
- test/testDownloader.js
> feat(downloader): forward headers

- CHANGELOG.md
- README.md
- docs/markdown.md
- package-lock.json
- package.json
- src/defaults/html.pipe.js
- src/html/data-sections.js
- src/html/fetch-data.js
- src/html/find-embeds.js
- src/schemas/mdast.schema.json
- src/schemas/secrets.schema.json
- src/utils/cache-helper.js
- test/fixtures/example-embeds.html
- test/fixtures/example-embeds.md
- test/fixtures/example.html
- test/testCacheHelper.js
- test/testDataEmbeds.js
PR for #593 
Read the writeup here to see how to use this: https://github.com/adobe/helix-pipeline/blob/data-embeds/docs/markdown.md
Ready to review when:
Ready to use when:
**Note: this branch has been rebased to master, hence some of the commits from #613 show up here.**
> Data Embeds

- package-lock.json
- package.json
- src/action.d.ts
- src/context.d.ts
- src/utils/Downloader.js
- src/utils/openwhisk.js
- test/testHTML.js
- test/testOpenwhisk.js
> fix(error): better error logging on download failures

- src/utils/Downloader.js
- test/testDownloader.js
> feat(downloader): add transaction id

- src/utils/embed-handler.js
- test/fixtures/embeds.html
- test/testDataEmbeds.js
PR for https://github.com/adobe/helix-pipeline/issues/662
> fix(embed): fix embed url construction

- package-lock.json
- package.json
- src/action.d.ts
- src/utils/Downloader.js
- test/testOpenwhisk.js
- test/utils.js
> fix(downloader): prevent open sockets

- src/html/remark-matter.js
- test/testFrontmatter.js
> fix(html): fix frontmatter detection

- src/html/data-sections.js
- src/html/fetch-data.js
- test/testDataEmbeds.js
PR for #714 
On my machine:
Before the test for a 5k dataset takes 2mins.
With this PR: 4.5s (10s on CircleCI).
Good improvement :)
> fix(data-embed): optimise data embeds to support large datasets

- src/html/parse-markdown.js
- src/html/remark-matter.js
- test/testFrontmatter.js
> fix(md): relax frontmatter complaining

- src/html/remark-matter.js
> feat(matter): make frontmatter less verbose

- src/utils/hast-util-to-dom.js
- src/utils/mdast-to-vdom.js
- test/testHTMLFromMarkdown.js
> fix(md): make pipeline more robust

- src/utils/Downloader.js
> feat(downloader): (fetch) use new AbortController instead of timeout

- package-lock.json
- package.json
- src/utils/openwhisk.js
- test/testOpenwhisk.js
needed for https://github.com/adobe/helix-publish/issues/585
> feat(status): add status check

- src/html/data-sections.js
- test/testDataEmbeds.js
> fix(data): prepare for new data-embed format

- src/utils/Downloader.js
- test/testHTML.js
> fix(downloader): avoid promise rejection errors for slow github

- package-lock.json
- package.json
- src/utils/mdast-to-vdom.js
- test/testHTMLFromMarkdown.js
> fix(md): correctly serialize inner html in raw elements

- src/utils/Downloader.js
> feat(log): info on 404

- .circleci/config.yml
- package-lock.json
- package.json
- src/html/data-sections.js
- test/testDataEmbeds.js
with this change, a list of internal embeds can be created out of a data embed
> feat(embeds): enable dynamic nesting of data embeds and internal embeds

- src/utils/is-production.js
- src/utils/timing.js
> Fix server timing and response headers

- src/html/fetch-content.js
> fix(content): fetch content using branch

- src/defaults/html.pipe.js
- src/html/fetch-content.js
- src/html/set-last-modified.js
- test/testFetchContent.js
- test/testHTML.js
relates to https://github.com/adobe/helix-content-proxy/pull/306 and https://github.com/adobe/helix-index-pipelines/issues/442
> fix(html.pipe): add last-modified to response

- src/html/fetch-data.js
- test/testDataEmbeds.js
> fix(embed): use data-embed v2

- src/utils/Downloader.js
> feat: re-enable Http/2

- package-lock.json
- package.json
- src/utils/hast-util-to-dom.js
- fix(deps): update dependency web-namespaces to v2
- build(deps): remove web-namespaces dependency
> remove web namespaces

- src/utils/dump-context.js
- src/utils/is-production.js
> fix(dump): don't write error dumps in production

- package-lock.json
- src/defaults/html.pipe.js
- src/html/rewrite-icons.js
- test/testHTMLFromMarkdown.js
> fix: rewrite icons in html tables
